#!/bin/bash
set -xe

cp /opt/app-root/src/extra/Apache/OpenProjectAuthentication.pm /etc/httpd/Apache

# delete existing directory
rm -rf /opt/app-root/src/files
ln -snf /opt/app-root/data/files /opt/app-root/src/files
