#!/bin/bash

sed -ie '/^\s*links.*api_experimental_query_path(query).*$/ { N; d; }' app/controllers/api/experimental/concerns/query_loading.rb

# delete existing directory
rm -rf /opt/app-root/src/files
ln -snf /opt/app-root/data/files /opt/app-root/src/files

# Fix source directory permissions
fix-permissions ./

mkdir -p /opt/app-root/data
chmod -R go+rwX /opt/app-root/data

