#!/bin/bash
set -xe

# run bundle to generate lockfile or else build
# will fail when bundle is called with --deployment
# this is mainly because plugins are set with
# environment variables in Gemfile.plugins
cd /tmp/src && bundle --path bundle --without sqlite3 development test
#cd /tmp/src && bundle --path bundle --without test

# delete resulting .bundle/cache or else there is
# a conflict with /tmp/src/.bundle/config
# when copying in assemble script
rm -rf /opt/app-root/src/.bundle
cd /tmp/src/frontend && npm install
