#!/bin/bash

if [[ -n "${OPENPROJECT_MANAGED_REPOS}" ]]; then
    ln -snf /tmp/src/config/configuration.yml /opt/app-root/etc/configuration.yml
fi
cd /tmp/src && bundle --path bundle
cd /tmp/src/frontend && npm install && bower install
